pull_request_rules:
  - name: automatic merge Dependabot pull requests
    conditions:
      - author~=dependabot\[bot\]|dependabot-preview\[bot\]
      - status-success=continuous-integration/travis-ci
    actions:
      merge:
        method: merge
