name: Validate the project version
on:
  pull_request:

concurrency:
  group: version-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Clone this git repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - name: Check that the project version is set in all CFN templates
        run: make cfn/version
